name: Check Python Version

on:
  push:
    branches:
      - main

jobs:
  check-python-version:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Display Python version
      run: python --version
